version: '3'

services:
  redis:
    image: redis:7.0.5-alpine
    env_file: .env
    command: redis-server --loglevel warning --requirepass $REDIS_PASSWORD
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
